add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are confguring is "character"
success_symbol = "[➜](bold green)"     # The "symbol" segment is being set to "➜"
error_symbol = "[➜](bold red)"

[aws]
format = 'on [$symbol($profile )]($style)'
[aws.region_aliases]
eu-west-1 = 'IRL'
